- name: csv
  gather_facts: false
  hosts: localhost
  tasks:
  - name: Path to CSV, delimeter $, register to object users, localhost
    community.general.read_csv:
      path: "./Alamogordo.csv"
      delimiter: $
    register: jinja
    delegate_to: localhost

  - name: Jinja Template
    template:
      src: "./ArubaOS_JINJA2.j2"
      dest: "/{{ item.hostname }}.cfg"
    loop: "{{ jinja.list }}"
