- name: csv
  gather_facts: false
  hosts: localhost
  vars:
    csvfile: "{{ lookup('file', 'svi.csv') }}"
  tasks:
  - name: Path to CSV, delimeter $, register to object users, localhost
    community.general.read_csv:
      path: "./Alamogordo.csv"
      delimiter: $
    register: jinja
    delegate_to: localhost

  - name: Parse CSV To YAML, This is vlan conversion
    template:
      src: "./svi.j2"
      dest: "/var/lib/awx/projects/_73__alamogordo/config/svi_output.cfg"
    run_once: true

  - name: Jinja Template
    template:
      src: "./Alamogordo.j2"
      dest: "/var/lib/awx/projects/_73__alamogordo/config/{{ item.hostname }}.cfg"
    loop: "{{ jinja.list }}"
